<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversalForm.JsonUtil\UniversalForm.Utils.csproj" />
    <ProjectReference Include="..\UniversalForm.Server.Persistence\UniversalForm.Server.Persistence.csproj" />
  </ItemGroup>

</Project>
